{{- if .Values.envSecrets }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "personality-test-backend.fullname" . }}-secrets
  labels:
    {{- include "personality-test-backend.labels" . | nindent 4 }}
type: Opaque
data:
{{- range $key, $value := .Values.envSecrets }}
{{- if $value }}
  {{ $key }}: {{ $value | b64enc | quote }}
{{- end }}
{{- end }}
{{- end }}
