apiVersion: v2
name: personality-test-frontend
description: Personality Test Frontend Application
type: application
version: 1.0.0
appVersion: 1.0.0
keywords:
  - personality-test
  - frontend
  - react
maintainers:
  - name: Bossbach
